# Generated by Django 3.1.7 on 2021-03-31 02:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
# test comment

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_role', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=280, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_title', models.CharField(max_length=200)),
                ('artwork_description', models.TextField(blank=True, max_length=280, null=True)),
                ('artwork_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('artwork_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_description', models.TextField(blank=True, max_length=280, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('rating_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist')),
                ('rating_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist')),
                ('favorite_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200)),
                ('collection_description', models.TextField(blank=True, max_length=280, null=True)),
                ('artwork', models.ManyToManyField(blank=True, to='gallery.Artwork')),
                ('collection_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_tag',
            field=models.ManyToManyField(blank=True, to='gallery.Tag'),
        ),
    ]
