# Generated by Django 3.1.6 on 2021-02-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210224_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
