# Generated by Django 3.1.7 on 2021-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_salesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleSummary',
        ),
        migrations.CreateModel(
            name='ArtworkSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Artwork Summary',
                'verbose_name_plural': 'Artwork Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.artwork',),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_created',
            field=models.DateTimeField(),
        ),
    ]
