# Generated by Django 3.1.6 on 2021-02-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile_picture',
        ),
    ]
