# Generated by Django 3.1.6 on 2021-02-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_artist_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_title', models.CharField(max_length=200)),
                ('artwork_description', models.TextField(max_length=280)),
                ('artwork_artist', models.ManyToManyField(to='gallery.Artist')),
            ],
        ),
    ]
