# Generated by Django 3.1.6 on 2021-02-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200)),
                ('collection_description', models.TextField(max_length=280)),
                ('collection_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.artist')),
            ],
        ),
    ]
