# Generated by Django 3.1.6 on 2021-02-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='artwork',
            field=models.ManyToManyField(to='gallery.Artwork'),
        ),
    ]
