# Generated by Django 3.1.6 on 2021-02-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_collection_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_description', models.TextField(max_length=280)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_tag',
            field=models.ManyToManyField(to='gallery.Tag'),
        ),
    ]
