# Generated by Django 3.1.6 on 2021-02-25 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
