# Generated by Django 3.1.6 on 2021-02-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_favorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favorites_artist',
            new_name='favorite_artist',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favorites_artwork',
            new_name='favorite_artwork',
        ),
    ]
