# Generated by Django 3.1.6 on 2021-02-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20210225_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_role',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_description',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_tag',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.Tag'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='artwork',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.Artwork'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_description',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_description',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
