# Generated by Django 3.1.6 on 2021-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20210227_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_tag',
            field=models.ManyToManyField(to='gallery.Tag'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='artwork',
            field=models.ManyToManyField(to='gallery.Artwork'),
        ),
    ]
