# Generated by Django 3.1.6 on 2021-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20210227_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_role',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_tag',
            field=models.ManyToManyField(blank=True, to='gallery.Tag'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='artwork',
            field=models.ManyToManyField(blank=True, to='gallery.Artwork'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite_artwork',
            field=models.ManyToManyField(blank=True, to='gallery.Artwork'),
        ),
    ]
