# Generated by Django 3.1.6 on 2021-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20210227_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_role',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
