# Generated by Django 3.1.6 on 2021-02-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20210227_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_role',
            field=models.BooleanField(default=False),
        ),
    ]
