# Generated by Django 3.1.6 on 2021-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_artist_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
